services:
  web:
    build: .
    ports: 
      - "127.0.0.1:${YTDLOR_WEB_PORT:-3000}:3000"
    volumes:
      - type: volume
        source: db
        target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
      RAILS_SERVE_STATIC_FILES: 1
    command: rails server
  default_worker:
    build: .
    volumes:
      - type: volume
        source: db
        target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
      VERBOSE: 1
      QUEUE: default
    command: rake resque:work
  thumbnail_worker:
    build: .
    volumes:
      - type: volume
        source: db
        target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
      VERBOSE: 1
      QUEUE: thumbnail
    command: rake resque:work
  video_worker:
    build: .
    volumes:
      - type: volume
        source: db
        target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: "redis://redis:6379/1"
      VERBOSE: 1
      QUEUE: video
    command: rake resque:work
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db:
  postgres:
  storage:
