services:
  db:
    image: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    build: .
    ports: 
      - "3000:3000"
      - "5678:5678"
    volumes:
      #- type: volume
      #  source: db
      #  target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: "redis://redis:6379/1"
      RAILS_SERVE_STATIC_FILES: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      MALLOC_ARENA_MAX: 2
    command: rails server
  default_worker:
    build: .
    volumes:
      #- type: volume
      #  source: db
      #  target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: "redis://redis:6379/1"
      VERBOSE: 1
      QUEUE: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      MALLOC_ARENA_MAX: 2
    command: rake resque:work
  thumbnail_worker:
    build: .
    volumes:
      #- type: volume
      #  source: db
      #  target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: "redis://redis:6379/1"
      VERBOSE: 1
      QUEUE: thumbnail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      MALLOC_ARENA_MAX: 2
    command: rake resque:work
  video_worker:
    build: .
    volumes:
      #- type: volume
      #  source: db
      #  target: /var/opt/ytdlor/db
      - type: volume
        source: storage
        target: /var/opt/ytdlor/storage
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      REDIS_URL: "redis://redis:6379/1"
      VERBOSE: 1
      QUEUE: video
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      MALLOC_ARENA_MAX: 2
    command: rake resque:work
  redis:
    image: redis
volumes:
  #db:
  storage:
  postgres_volume:
